---
title: "BIRAX study - Figures for Macula Society conference presentation"
author: "David M Wright - d.wright@qub.ac.uk"
date: "Document compiled: `r Sys.Date()`"
output: 
  bookdown::html_document2:
  toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
library(rprojroot)
library(tidyverse)
library(broom)
```

`r R.version.string`   


```{r run-analysis, include=FALSE}
source(find_rstudio_root_file("Code/BIRAX-assemble-cohort.R"))
```


```{r fluid-baseline-boxplot-age, fig.cap= "Baseline fluid volumes by age group.", warning=FALSE, fig.width=11, fig.height=7}
fluid_history %>% 
  filter(baseline) %>% 
  inner_join(eye, by = c("PatientID", "EyeCode")) %>%
  mutate(across(Age, as.factor)) %>% 
  select(Age, SRFVolumeNl, IRFVolumeNl, TRFVolumeNl) %>% 
  pivot_longer(cols = c(SRFVolumeNl, IRFVolumeNl, TRFVolumeNl), names_to = "Variable", values_to = "Volume") %>% 
  ggplot(aes(x = Age,  y = Volume, fill = Variable)) +
  geom_boxplot(outlier.shape = NA)+
   coord_cartesian(ylim = c(0, 1500)) +
  theme_light() +
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14), legend.text = element_text(size = 14)) +
  labs(fill = NULL)
```

```{r fluid-baseline-boxplot-gender, fig.cap= "Baseline fluid volumes by gender.", warning=FALSE, fig.width=9, fig.height=7}
fluid_history %>% 
  filter(baseline) %>% 
  inner_join(eye, by = c("PatientID", "EyeCode")) %>%
  select(Gender, SRFVolumeNl, IRFVolumeNl, TRFVolumeNl) %>% 
  pivot_longer(cols = c(SRFVolumeNl, IRFVolumeNl, TRFVolumeNl), names_to = "Variable", values_to = "Volume") %>% 
  ggplot(aes(x = Gender,  y = Volume, fill = Variable)) +
  geom_boxplot(outlier.shape = NA)+
   coord_cartesian(ylim = c(0, 1500)) +
  theme_light() +
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14), legend.text = element_text(size = 14)) +
  labs(fill = NULL)
```


```{r injections-per-year-boxplot, fig.cap="Injections by treatment year.", fig.width=9, fig.height=7}
injections %>% 
  count(PatientID, EyeCode, treatment_year, name = "Injections") %>% 
  select(treatment_year, Injections) %>% 
  ggplot(aes(x = treatment_year, y = Injections)) +
  geom_boxplot(fill = "lightblue") +
  theme_light() +
  scale_y_continuous(breaks = function(lims){0:lims[2]}, limits = c(0, NA)) +
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14), legend.text = element_text(size = 14)) +
  labs(x = "Treatment Year")

```
```{r amd-type-by-year, fig.cap= "Fluid types by treatment year.", fig.width=9, fig.height=6}
injections %>% 
  inner_join(
  fluid_history %>% 
  filter(baseline) %>% 
  select(PatientID, EyeCode, amd_type)
  , by = c("PatientID", "EyeCode")) %>% 
  group_by(amd_type) %>% 
  count(amd_type, PatientID, EyeCode, treatment_year, name = "Injections") %>% 
  count(amd_type, treatment_year) %>% 
  group_by(treatment_year) %>% 
  mutate(perc = n/sum(n)*100) %>% 
  ggplot(aes(x = treatment_year)) +
  geom_col(aes(y = perc, fill = amd_type)) +
  labs(fill = NULL, x = "Treatment Year", y = "% eyes") +
  theme_light() +
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14), legend.text = element_text(size = 14)) 
```

```{r treatment-series, fig.cap="Sample patient histories. Dotted lines indicate injection dates.", fig.width=9, fig.height=7, warning = FALSE}

plot_pt_history <- function(ptid){
  
bind_rows(
  filter(fluid_history, PatientID == ptid[1], EyeCode == ptid[2]) %>% 
    pivot_longer(cols = c(SRFVolumeNl, IRFVolumeNl), names_to = "Variable") %>% 
  transmute(treatment_months, name = "Fluid", Variable, value)
,
  filter(va_history, PatientID == ptid[1], EyeCode == ptid[2]) %>% 
  transmute(treatment_months, value = va_etdrs, name = "Visual Acuity", Variable = "ETDRS Letters")
) %>% 
  
  ggplot(aes(x = treatment_months, y = value)) +
  geom_line(aes(colour = Variable), linewidth = 1) +
  facet_wrap(~name, ncol = 1, scales = "free_y") +
  
  geom_vline(xintercept = treatment_intervals %>% 
  filter(PatientID == ptid[1], EyeCode == ptid[2]) %>% pull(treatment_months),
  lty = 2) +
    scale_x_continuous(minor_breaks = NULL) +
  theme_light() +
  theme(axis.text = element_text(size = 14), axis.title = element_text(size = 14), legend.text = element_text(size = 14))  +
  labs(y = NULL, x = "Treatment Month", colour = NULL, title = ptid)
  
}
# plot_pt_history(unlist(select(slice_sample(eye, n= 1), PatientID, EyeCode)))
plot_pt_history(c("1DFDAC5A-0C94-33CE-098A-5BAE47F5EF9C", "L"))
plot_pt_history(c("AC43F415-F993-9DA0-22ED-23A7668BBA2A", "R"))
plot_pt_history(c("04231639-7121-5221-F31B-4374B4B82D84", "R"))

```




